# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rmn < Formula
  desc "CLI tool for interacting with Redmine"
  homepage "https://github.com/nbifrye/rmn"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nbifrye/rmn/releases/download/v0.1.0/rmn_0.1.0_darwin_amd64.tar.gz"
      sha256 "fc8b8b237d2d8b0f63a76be73d8e6e7ab7a38255c2dad3ef92f80240daada33a"

      define_method(:install) do
        bin.install "rmn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nbifrye/rmn/releases/download/v0.1.0/rmn_0.1.0_darwin_arm64.tar.gz"
      sha256 "67f476ddae8828bf2d86daad245190048de34980ee70d3ef1c3f3a016771f39e"

      define_method(:install) do
        bin.install "rmn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nbifrye/rmn/releases/download/v0.1.0/rmn_0.1.0_linux_amd64.tar.gz"
      sha256 "c0accede29f7760baeb75d3baa1c70fe5ec935baa088bcacc1ed256e995895fe"
      define_method(:install) do
        bin.install "rmn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nbifrye/rmn/releases/download/v0.1.0/rmn_0.1.0_linux_arm64.tar.gz"
      sha256 "e96c60dcef7d6e2f1ee8a820e0fa38e58a0a69f66869bdc7afe4d3209c8dc0dc"
      define_method(:install) do
        bin.install "rmn"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rmn --version")
  end
end
